bin: Refactor

diff --git a/bin/py_simplehttpserver b/bin/py_simplehttpserver
--- a/bin/py_simplehttpserver
+++ b/bin/py_simplehttpserver
@@ -3,7 +3,14 @@
 major_version=$(python --version 2>&1 | grep -o '[0-9].[0-9].[0-9]' | cut -d'.' -f1)
 
 case $major_version in
-    2) python -m SimpleHTTPServer;;
-    3) python -m http.server;;
-    *) echo 'error'; exit 1;;
+    2)
+        python -m SimpleHTTPServer
+        ;;
+    3)
+        python -m http.server
+        ;;
+    *)
+        echo 'error'
+        exit 1
+        ;;
 esac
